### ISSUE TITLE
When a manual tab group is created in chrome, mirror that in auto-group-tabs

### ISSUE THREAD

**Issue by MuttCollective** [loilo/auto-group-tabs#14]
I find myself creating manual groups first directly in the browser when I start launching multiple pages and then secondly go to auto-group-tabs and add the same. This might be self induced double work but it would be great if any manually created tabs in chrome were automatically pulled into auto-group and optimally a refresh would then be done to pull in any existing matching tabs.

**Comment by loilo** [comment]
I don't really like the idea to mirror all manual tab groups to the extension's configuration. However, there is an upcoming feature in the next days that will remove the double work you're facing — see my comment [here](https://github.com/loilo/auto-group-tabs/issues/8#issuecomment-1222467471).

**Comment by loilo** [comment]
This feature has been published, new version 0.0.14 is out. This makes it easy to create configurations from manual tab groups by clicking the extension icon.
