### ISSUE TITLE
Does not work for IP addresses

### ISSUE THREAD

**Issue by poiromaniax** [loilo/auto-group-tabs#17]
I have a self hosted app that I access using the machine IP address.

I cant seem to get Auto Group to work with this. It doesnt create the group to begin with.

I tried:

xx.xx.xx.xx
https://xx.xx.xx.xx/
xx.xx.xx.xx/*
*/xx.xx.xx.xx

**Comment by loilo** [comment]
Good point, this is not something I've tested. I'll take a look.

**Comment by loilo** [comment]
Mh, I'm not sure what the problem in your case could be. I've tested with my local router and it works just like it should. 🤔 
![Screenshot of the extension group configuration, showing a group named "fritz.box!" and a matcher pattern of "192.168.178.1/*"](https://user-images.githubusercontent.com/1922624/158057973-3a372633-49ca-45ce-99fb-08c7ba3c8eea.png)

**Comment by poiromaniax** [comment]
It allows me to put the IP in but it didnt create the group or move the tab to it

**Comment by loilo** [comment]
Sorry, I can't really help you without having a reproducible example. I understand if you don't want to share a public IP here, but maybe you can create a similar case as I did with a local IP and share that (if it doesn't work either)?

**Comment by poiromaniax** [comment]
Ok so I found the solution and now I feel a bit idiotic

Its running on a custom port, I needed to include the custom port in the URL field and now it works

Thanks anyway!

**Comment by loilo** [comment]
Happens to the best. 😉 
Good to hear it's working now. 👍
