### ISSUE TITLE
Feature request: port wildcard

### ISSUE THREAD

**Issue by Guris** [loilo/auto-group-tabs#19]
Hi. It would be great if url pattern supports wildcard for port number.

Would be much appreciated typically for local development: `http://localhost:*/*`

Thanks for considering this....

**Comment by loilo** [comment]
You're right, this should work. Or rather, it should not be necessary — a bare host specifier with no wildcard just match any port.
I'll take care of this.

**Comment by loilo** [comment]
I have fixed this issue and submitted a new extension version. It will take a couple days (until monday or tuesday) until it is reviewed and published, but then using a simple `localhost/*` should work for your case.

**Comment by Guris** [comment]
Hi. There's still version 0.0.7 on Chrome Web store. I'm looking forward for the 0.0.8 update but it's not coming... 
Do you have any info why?

**Comment by loilo** [comment]
Oof. Seems like I had _uploaded_ the new version to the Google Developer Dashboard but forgot to submit it for review. 🙄 
Very sorry, have done that now and the release should come probably sometime this week. Thanks for the pointer.

**Comment by loilo** [comment]
Looks good. 👍 

<img width="131" alt="Screenshot from the Chrome Web Store showing the version number 0.0.8" src="https://user-images.githubusercontent.com/1922624/163201912-f7315b8b-fc5d-44f8-86e5-28cc7749a5c0.png">

**Comment by Guris** [comment]
It's there and working. Great job. Thanks!

**Comment by Guris** [comment]
Hi. Suddenly it stopped working (without updating, still on v0.0.10). Probably some Chrome update broke this?

Not working (wen localhost has port number):
- localhost
- localhost:*
- localhost/*

Working:
- localhost:1234

**Comment by loilo** [comment]
Oof. You're absolutely right. I made some changes to the matcher patterns and it seems I broke URLs with ports in the process. Sorry, I'll push a fix right now, but review & release on the side of Chrome might take until start of next week. 😶

Side note: I really should add some sort of automated tests, can't keep breaking other peoples' use cases all the time. 😓

**Comment by Guris** [comment]
Thank you.
Tests are surely great solution to this unforeseen functionality breaks...

Appreciate your willingness and speed 😉

**Comment by loilo** [comment]
Version 0.0.11 is submitted for review with a fix for this problem.

> Thank you.

You're welcome, thanks for the report.

> Appreciate your willingness and speed 😉

Willingness usually is not the problem, the bottleneck is time to spare. 😋

> Tests are surely great solution to this unforeseen functionality breaks...

Indeed. No clue how to do this for browser extensions, but probably Playwright et al can help me there. Getting started with that is another huge time sink, so I'm not sure when it will actually come around to this. 🤷‍♂️

---

In case you're interested what caused the bug: I previously enforced hosts to either have a period in them or be `localhost` (with an optional port). So ports were always broken for non-localhost URLs.
Then somebody made me aware that hosts may indeed be arbitrary alphanumeric strings (like `intranet`) if the DNS is configured accordingly. So I relaxed the host rule, dropped the enforcement of the period character and, as it was no longer necessary, also dropped the special case of `localhost`.
...aaand as you can guess, I dropped the optional port as well, so ports no longer work with any URL now.

(That said, with the 0.0.11 fix, ports will work with all hostnames.)

**Comment by loilo** [comment]
Just realized that 0.0.11 has already been released yesterday. Can you confirm your patterns work again @Guris?

**Comment by Guris** [comment]
Works like a charm again!
Thanks a lot...

Just sumbled upon Playwright as well and seems useful even for Chrome Extensions ([docs](https://playwright.dev/docs/chrome-extensions)) 😉
