### ISSUE TITLE
Supporting extension:// URLs

### ISSUE THREAD

**Issue by openclosure** [loilo/auto-group-tabs#27]
Hi, fantastic work with this extension. I use it daily and find it very helpful for managing dozens of tabs at the same time without getting lost. I see that you added support for `file://` URLs. I was wondering if you would consider supporting `extension://` URLs as well. 

For me I use this extension in combination with the extension The Great Suspender. The problem is, once a tab is suspended, it has it's URL turned into something like `extension://jaekigmclikkalnicnjoafgfjoefkpeg/[a bunch of metadata about the tab]&url=[original url]`. In theory I would like to just prepend `*` to all my rules and have them auto-sorted the same as a regular tab, but they are ignored by the extension right now.

**Comment by loilo** [comment]
This should definitiely be possible, I'll take a look.

**Comment by loilo** [comment]
I have just pushed a new extension version (0.0.13) which fixes this problem. It still needs to pass the review process before being published, but that should take just a couple days.

**Comment by openclosure** [comment]
Worked perfectly! Only minor issue on my side is that the URLs in the extension scheme are encoded (eg, "/" -> "%2F"), but not really your problem, and easy to work around with some more manual rule setup. Thanks again, your extension is by far the fastest and most reliable tab group organizer I've used.

**Comment by loilo** [comment]
Happy to hear, thanks. :)
