### ISSUE TITLE
grouping when subdomains are present

### ISSUE THREAD

**Issue by davidfrantz** [loilo/auto-group-tabs#3]
Hi there,

this is an awesome extension, which I have waited for since tab groups were released! As I really like the groups, but the creation kind of annoys me, I stumbled on this extension.

The tool works great in general, I just have a small issue, which admittedly could be related to usage.

How can I group based on a pattern like this? Do I need to use some sort of wildcards?

Pattern:
github.com
github.io

Expected grouping:
https://github.com/davidfrantz
https://davidfrantz.github.io/

Only the first one is being grouped.

Cheers,
David

**Comment by loilo** [comment]
Hey @davidfrantz, glad you like the extension.
Yes, you can use wildcards — more specifically, you can use [match patterns](https://developer.chrome.com/docs/extensions/mv3/match_patterns/).

There should be a linked info button when you focus the URL pattern field, like this:

![Screenshot: Info button shown when focusing the URL pattern field](https://user-images.githubusercontent.com/1922624/113768954-bbc61280-9720-11eb-91cb-07bf4fbacec0.png)

But just when I checked this, I realized that the info button sometimes only showed in the URL pattern field of the *first* group — definitely something I should investigate. 🤔 

Regarding your concrete case: `*.github.com` and `*.github.io` should be the patterns you want. They match all subdomains of `github.com` and `github.io`, as well as the domains themselves.

**Comment by davidfrantz** [comment]
Thanks @loilo !
