### ISSUE TITLE
Can you set priority for the matching rules ？

### ISSUE THREAD

**Issue by Rainerhu** [loilo/auto-group-tabs#40]
I like the extension.
Can you set priority for the matching rules that have been set? I would like to set a broad rule to match most web sites to one group, and then further set some precise rules to other groups that I have specified.
etc：
group：google   rule：*.google.com
group： mail     rule： mail.google.com

**Comment by loilo** [comment]
Hey @Rainerhu

There is no complex mechanism to apply priorities to individual URL patterns, but you can prioritize whole group configurations by sorting them.

To do that, go to the extension options and find the Sort button at the bottom:

<img width="64" alt="Screenshot of a button showing an upwards and downwards arrow next to each other" src="https://github.com/loilo/auto-group-tabs/assets/1922624/ab33435a-a09d-43d0-a72e-871044c1f6f1">

If you activate that button, you can sort your group configurations. Configurations will be evaluated in the order they appear there, i.e. you'd want to put your broader configurations (e.g. `*.google.com`) below the more specific ones.

Did this achieve what you needed it to do?

**Comment by Rainerhu** [comment]
Oh，Thanks，It's what I  need
