### ISSUE TITLE
Closing all tabs in a group doesn't seem to work anymore

### ISSUE THREAD

**Issue by thecontstruct** [loilo/auto-group-tabs#45]
![Screenshot 2024-02-26 at 1 02 53 PM](https://github.com/loilo/auto-group-tabs/assets/4115757/0dbb9c37-5106-47df-af76-1a6f83eae958)

I could've sworn there used to be a way to close the group when you right click on the group label, am I missing something?

**Comment by loilo** [comment]
Yep, Chrome renamed it, it's "Delete Group" now. I guess some people found it confusing that "Close Group" did actually remove the group, not collapse it.

**Comment by loilo** [comment]
So, just for clarity: When you click "Delete Group", it will _not_ delete your auto-grouping configuration.

**Comment by thecontstruct** [comment]
Got it! thanks
