### ISSUE TITLE
[Feature] Remove non matching tab from group

### ISSUE THREAD

**Issue by magnus-lundberg-discovery** [loilo/auto-group-tabs#46]
It would be great if it was possible to specify that tabs that do not match a group should be removed from that group and dumped somewhere else. Currently if you follow a link in a grouped tab and that link does not match any other group that tab is kept in its original group

**Comment by loilo** [comment]
That option already exists, if only on a per-group basis. It's called "Strict" and can be found under "Advanced Settings":

<img width="389" alt="image" src="https://github.com/loilo/auto-group-tabs/assets/1922624/29a37b84-7394-41f5-96f2-cd33ea4ab15c">

**Comment by HaroldAlingGSD** [comment]
Ah, I didn't open the 'advanced settings'. Sorry!
