### ISSUE TITLE
[feature] Auto create patterns for domains with more than _ open tabs

### ISSUE THREAD

**Issue by yonisade** [loilo/auto-group-tabs#47]
To save time, I would like to have an option for the extension to auto create URL patterns for domains with more than `_` open tabs, `_` being a numeric picker field.

The domain name should be the tab group label.

**Comment by loilo** [comment]
I consider that kind of feature out of scope for this extension. The extension is designed for more sophisticated grouping rules than just aggregating tabs by domain.

That said, there's already extensions out there that do this. Maybe you'll be happy with the [Group Tabs by Domain](https://chromewebstore.google.com/detail/icmbnkmjhdapliaologdghjfpcmcimln) extension.
