### ISSUE TITLE
Rules not always applied to tabs opened from external app with redirect

### ISSUE THREAD

**Issue by Guris** [loilo/auto-group-tabs#6]
Hi.
>Great extension - thanks for this.

### Steps to reproduce:
1. Create tab group, e.g. _Task_ with rule:
![image](https://user-images.githubusercontent.com/1776912/119611476-05ff7200-bdfb-11eb-9476-4df394da98e8.png)
2. Open link from external app (Outlook, MS Teams...) which has redirect (not changing domain mentioned in the rule)
3. Link is opened in new tab and not added to _Task_ group

### But it's not always the case:
- Sometimes link is processed correctly and added to to group.
- Entering the url directly into address bar results in correct addition to group (always)

### Sample urls (from TargetProcess):
`https://mycompany.tpondemand.com/entity/12345`
results into
`https://mycompany.tpondemand.com/restui/board.aspx?#page=request/12345`

**Comment by loilo** [comment]
Hey there, I'm aware of this problem, thanks for putting it into an issue. I'll take a look at this.

**Comment by loilo** [comment]
Auto-Group Tabs v0.0.6 was just released and should fix this – tabs should now be grouped very reliably.

I'll close this now, but feel free to re-open if anything does still not work as expected.
