### ISSUE TITLE
Tab not added to group when opened in another group

### ISSUE THREAD

**Issue by Guris** [loilo/auto-group-tabs#7]
### Scenario
- _Group A_ with rule to add pages from domain A
- _Group B_ with rule to add pages from domain B
- Page on domain A contains link which
  - leads to domain B page
  - opens link in new tab

### Expected behavior
New tab is added to _Group B_

### Current behavior
New tab opens in _Group A_

**Comment by loilo** [comment]
This refers to the same issue as #5.
As described there, this behavior is intentional, but I intend to offer an option to control it.

I'll close this as a duplicate, please subscribe to #5 to get notified about progress on this. 🙂
