### ISSUE TITLE
Add quick action panel functionality

### ISSUE THREAD

**Issue by loilo** [loilo/auto-group-tabs#8]
Clicking the extension icon could spawn a panel with quick actions like "Add to group" etc.

_via web store review by Marius Franzke_

**Comment by rolltidehero** [comment]
Would love this option to "Add this domain to a group"

**Comment by loilo** [comment]
A little heads-up on this: This feature is on its way. 🙂 
I have already fully implemented it, just going to take a couple days to test it in day-to-day usage. (I have broken stuff in extension updates before, so I'm a little wary of just hitting the publish button.)

Here is a feature list and a couple screenshots as "appetizers". 😉 

**Workflow:**

- Click the extension icon
- Insert a single or multiple URL patterns
- Select a group configuration
- Hit the "Save new patterns" button

**Helpful goodies:**

- Go to the full-blown extension options UI with a single button click. ("More options")
- Suggestion buttons for common patterns, depending on the current tab's URL. Using them prefills the URL pattern field(s).
- New group configurations can be created directly from the "Select group" dropdown (last item is a "Create group" button)
- If the current tab is inside an already configured group, that group's configuration will be preselected in the "Select group" dropdown. Also, a "Show all rules for <group name>" button will be shown to edit the group as a whole. (screenshot 2)
- If the current tab is inside a group that has not been configured yet, a group configuration with the appropriate title and color can be created on the fly from the "Select group" dropdown. (screenshot 3)

---

**Opened from a tab inside an existing configured group**

<img width="835" alt="" src="https://user-images.githubusercontent.com/1922624/185945040-91dda3b8-c3d6-420d-a3af-ae71e58adca8.png">

---

**Opened from a tab with no group**

<img width="834" alt="" src="https://user-images.githubusercontent.com/1922624/185945499-99bc160e-dfbb-4200-8af4-88214da0e22d.png">

---

**Opened from a tab with a manual group (i.e. the group has no auto-group configuration yet)**

<img width="830" alt="" src="https://user-images.githubusercontent.com/1922624/185947397-42c7cff7-052d-4ce0-bf2c-f7747207f931.png">

**Comment by loilo** [comment]
This is out as version 0.0.14 — have fun with it. 🙂
